app = "lol-active"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "npm start"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 128
  processes = ["app"]

[deploy]
  strategy = "immediate"
  release_command = "npm install"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "lol_active_data"
  destination = "/app/data"

[metrics]
  port = 8081
  path = "/metrics" 